# Generated by Django 5.0.1 on 2025-09-15 19:20

import django.core.validators
import django.db.models.deletion
import spaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Space name (2-100 characters)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the space",
                        max_length=500,
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        default=spaces.models.generate_invite_code,
                        help_text="6-character invite code for joining",
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this space is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this space",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Space",
                "verbose_name_plural": "Spaces",
                "db_table": "spaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpaceMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this membership is active"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spaces.space"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Space Member",
                "verbose_name_plural": "Space Members",
                "db_table": "space_members",
                "ordering": ["role", "joined_at"],
                "unique_together": {("space", "user")},
            },
        ),
        migrations.AddField(
            model_name="space",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="spaces",
                through="spaces.SpaceMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
