# Generated by Django 5.0.1 on 2025-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacemember",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Whether this is the user's default space"
            ),
        ),
    ]
