# Generated by Django 5.0.1 on 2025-09-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0002_spacemember_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "🔵 Blue"),
                    ("green", "🟢 Green"),
                    ("red", "🔴 Red"),
                    ("purple", "🟣 Purple"),
                    ("yellow", "🟡 Yellow"),
                    ("orange", "🟠 Orange"),
                    ("pink", "🩷 Pink"),
                    ("teal", "🟢 Teal"),
                    ("indigo", "🟣 Indigo"),
                    ("gray", "⚫ Gray"),
                ],
                default="blue",
                help_text="Color theme for this space",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="icon",
            field=models.CharField(
                choices=[
                    ("home", "🏠 Home"),
                    ("wallet", "💰 Wallet"),
                    ("heart", "❤️ Heart"),
                    ("star", "⭐ Star"),
                    ("family", "👨\u200d👩\u200d👧\u200d👦 Family"),
                    ("travel", "✈️ Travel"),
                    ("work", "💼 Work"),
                    ("shopping", "🛍️ Shopping"),
                    ("food", "🍽️ Food"),
                    ("car", "🚗 Car"),
                    ("house", "🏡 House"),
                    ("business", "🏢 Business"),
                ],
                default="wallet",
                help_text="Icon for this space",
                max_length=20,
            ),
        ),
    ]
