# Generated by Django 5.0.1 on 2025-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0003_space_color_space_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this space was archived (null if not archived)",
                null=True,
            ),
        ),
    ]
