# Generated by Django 5.0.1 on 2025-09-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0004_space_archived_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_mode",
                    models.CharField(
                        choices=[
                            ("none", "Sin aprobaciones - Cambios libres"),
                            ("all", "Todos los cambios requieren aprobación"),
                            ("percentage", "Solo cambios mayores a X%"),
                            ("custom", "Reglas personalizadas"),
                        ],
                        default="percentage",
                        help_text="How budget changes should be approved",
                        max_length=20,
                    ),
                ),
                (
                    "approval_percentage_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Minimum percentage change that requires approval",
                        max_digits=5,
                    ),
                ),
                (
                    "approval_timeout_days",
                    models.IntegerField(
                        default=3,
                        help_text="Days to wait before auto-approving pending changes",
                    ),
                ),
                (
                    "notifications_in_app",
                    models.BooleanField(
                        default=True, help_text="Send in-app notifications"
                    ),
                ),
                (
                    "notifications_email",
                    models.BooleanField(
                        default=False, help_text="Also send email notifications"
                    ),
                ),
                (
                    "shared_expenses_require_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Shared expenses always require approval",
                    ),
                ),
                (
                    "recurring_changes_require_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Changes to recurring items require approval",
                    ),
                ),
                (
                    "deletion_requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Deleting budget items requires approval",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "space",
                    models.OneToOneField(
                        help_text="Space these settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Space Settings",
                "verbose_name_plural": "Space Settings",
                "db_table": "space_settings",
            },
        ),
    ]
