# Generated by Django 5.0.1 on 2025-09-16 20:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spaces", "0004_space_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (max 50 characters)", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the category",
                        max_length=200,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("home", "🏠 Home"),
                            ("zap", "⚡ Utilities"),
                            ("shopping-cart", "🛒 Food"),
                            ("car", "🚗 Transport"),
                            ("heart", "❤️ Health"),
                            ("music", "🎵 Entertainment"),
                            ("gift", "🎁 Shopping"),
                            ("piggy-bank", "🐷 Savings"),
                            ("credit-card", "💳 Debt"),
                            ("more-horizontal", "📋 Other"),
                        ],
                        default="more-horizontal",
                        help_text="Icon for this category",
                        max_length=20,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("variable", "Variable")],
                        default="variable",
                        help_text="Whether this is a fixed or variable expense",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue",
                        help_text="Color theme for this category",
                        max_length=20,
                    ),
                ),
                (
                    "is_system_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a system-provided default category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this category is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this custom category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        help_text="Space this category belongs to (null for system defaults)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Category",
                "verbose_name_plural": "Budget Categories",
                "db_table": "budget_categories",
                "ordering": ["is_system_default", "name"],
                "unique_together": {("space", "name")},
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budgeted amount for this category",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "month_period",
                    models.CharField(
                        help_text="Budget month in YYYY-MM format", max_length=7
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this budget",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this budget is active"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for this budget category (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        help_text="Space this budget belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="spaces.space",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Budget category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="budgets.budgetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budgets",
                "ordering": ["-month_period", "category__name"],
                "unique_together": {("space", "category", "month_period")},
            },
        ),
    ]
