# Generated by Django 5.0.1 on 2025-09-18 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="expected_day",
            field=models.IntegerField(
                blank=True,
                help_text="Day of month when this expense is expected (1-31)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="is_estimated",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is an estimated amount (like utilities) vs fixed (like rent)",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="is_recurring",
            field=models.BooleanField(
                default=False, help_text="Whether this is a recurring expense"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="next_due_date",
            field=models.DateField(
                blank=True,
                help_text="Next expected date for this recurring expense",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="recurrence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                help_text="How often this expense recurs",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ActualExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual amount spent",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "date_paid",
                    models.DateField(help_text="Date when this expense was paid"),
                ),
                (
                    "month_period",
                    models.CharField(
                        help_text="Month this expense belongs to (YYYY-MM format)",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the expense",
                        max_length=200,
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True, help_text="URL to receipt image (Cloudinary, etc.)"
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense is shared among multiple users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_item",
                    models.ForeignKey(
                        help_text="Budget item this expense belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_expenses",
                        to="budgets.budget",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        help_text="User who paid this expense",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Expense",
                "verbose_name_plural": "Actual Expenses",
                "db_table": "actual_expenses",
                "ordering": ["-date_paid"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of expense this user is responsible for",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated amount for this user",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="budgets.actualexpense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User responsible for this portion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Split",
                "verbose_name_plural": "Expense Splits",
                "db_table": "expense_splits",
                "unique_together": {("actual_expense", "user")},
            },
        ),
    ]
