# Generated by Django 5.0.1 on 2025-09-18 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0002_budget_expected_day_budget_is_estimated_and_more"),
        ("spaces", "0005_spacesettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("amount", "Change amount"),
                            ("assignment", "Change assignment"),
                            ("date", "Change date"),
                            ("recurrence", "Change recurrence"),
                            ("delete", "Delete item"),
                            ("create", "Create new item"),
                        ],
                        help_text="Type of change being requested",
                        max_length=20,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        default=dict, help_text="Original values before change"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(default=dict, help_text="Proposed new values"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_approved", "Auto-approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                (
                    "required_approvals",
                    models.IntegerField(
                        default=1, help_text="Number of approvals required"
                    ),
                ),
                (
                    "received_approvals",
                    models.IntegerField(
                        default=0, help_text="Number of approvals received"
                    ),
                ),
                (
                    "auto_approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this was auto-approved due to timeout",
                        null=True,
                    ),
                ),
                (
                    "auto_approval_reason",
                    models.CharField(
                        blank=True, help_text="Reason for auto-approval", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this request expires and gets auto-approved"
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        help_text="Budget item being changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="budgets.budget",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User requesting the change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Change Request",
                "verbose_name_plural": "Budget Change Requests",
                "db_table": "budget_change_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeHistoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        help_text="Type of change that was made", max_length=20
                    ),
                ),
                ("old_value", models.JSONField(help_text="Values before the change")),
                ("new_value", models.JSONField(help_text="Values after the change")),
                (
                    "was_auto_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this change was auto-approved due to timeout",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who approved this change",
                        related_name="approved_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        help_text="The change request that caused this change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_logs",
                        to="budgets.budgetchangerequest",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who requested the change",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        help_text="Space where the change occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change History Log",
                "verbose_name_plural": "Change History Logs",
                "db_table": "change_history_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BudgetChangeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("approve", "Approve"), ("reject", "Reject")],
                        help_text="The vote cast",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for the vote",
                        max_length=500,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="budgets.budgetchangerequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who cast this vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "budget_change_votes",
                "ordering": ["-voted_at"],
                "unique_together": {("change_request", "user")},
            },
        ),
    ]
