# Generated by Django 5.0.1 on 2025-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0004_budget_actual_spend_dates_budget_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualexpense",
            name="month_period",
            field=models.CharField(
                blank=True,
                help_text="Month this expense belongs to (YYYY-MM format)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="actual_spend_dates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Historical dates when this expense was actually paid (for pattern analysis)",
            ),
        ),
    ]
