# Generated by Django 5.0.1 on 2025-09-24 14:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0005_alter_actualexpense_month_period_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgettemplate",
            name="default_category",
        ),
        migrations.RemoveField(
            model_name="budgettemplate",
            name="default_is_recurring",
        ),
        migrations.RemoveField(
            model_name="budgettemplate",
            name="default_recurrence_pattern",
        ),
        migrations.RemoveField(
            model_name="budgettemplate",
            name="default_reminder_days",
        ),
        migrations.RemoveField(
            model_name="budgettemplate",
            name="default_time_of_day",
        ),
        migrations.RemoveField(
            model_name="budgettemplate",
            name="default_timing_type",
        ),
        migrations.RemoveField(
            model_name="budgettemplate",
            name="suggested_amount",
        ),
        migrations.AddField(
            model_name="budget",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Whether this was created from scratch vs template",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to create this budget (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budgets.budgettemplate",
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="category_data",
            field=models.JSONField(
                default=dict,
                help_text="Category allocations as JSON: {category_name: {percentage: 50, amount: 1825, section: 'NECESIDADES'}}",
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="color_scheme",
            field=models.CharField(
                default="blue",
                help_text="Color scheme for this template",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="default_total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3650.00"),
                help_text="Default total monthly amount for calculations",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="framework_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("50_30_20", "50/30/20 Rule"),
                    ("zero_based", "Zero-based Budget"),
                    ("60_20_20", "60/20/20 Aggressive"),
                ],
                help_text="Specific framework type (only for framework templates)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="icon",
            field=models.CharField(
                default="wallet",
                help_text="Icon identifier for this template",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="sections_data",
            field=models.JSONField(
                default=dict,
                help_text="Section groupings as JSON: {'NECESIDADES': {percentage: 50, color: 'green', categories: [...]}",
            ),
        ),
        migrations.AddField(
            model_name="budgettemplate",
            name="situation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casa", "Casa"),
                    ("roommates", "Roommates"),
                    ("viaje_negocios", "Viaje de Negocios"),
                    ("plan_evento", "Plan Evento"),
                    ("oficina_negocio", "Oficina/Negocio"),
                ],
                help_text="Specific situation type (only for situation templates)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budgettemplate",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of when to use this template",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="budgettemplate",
            name="name",
            field=models.CharField(
                help_text="Template name (e.g., '50/30/20 Rule', 'Casa')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="budgettemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("framework", "Framework Financiero"),
                    ("situation", "Situación Práctica"),
                ],
                help_text="Type of template (framework or situation)",
                max_length=20,
            ),
        ),
    ]
