# Generated by Django 5.0.1 on 2025-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0006_remove_budgettemplate_default_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("housing", "Housing & Utilities"),
                            ("food", "Food & Dining"),
                            ("transportation", "Transportation"),
                            ("healthcare", "Healthcare"),
                            ("entertainment", "Entertainment"),
                            ("shopping", "Shopping & Personal"),
                            ("education", "Education & Learning"),
                            ("savings", "Savings & Investment"),
                            ("debt", "Debt & Loans"),
                            ("subscriptions", "Subscriptions & Services"),
                            ("pets", "Pet Care"),
                            ("family", "Family & Children"),
                            ("travel", "Travel & Vacation"),
                            ("business", "Business & Professional"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_popular", "-usage_count", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="budgets_cat_name_a7b45b_idx"),
                    models.Index(
                        fields=["category_type"], name="budgets_cat_categor_9e74e4_idx"
                    ),
                    models.Index(
                        fields=["-usage_count"], name="budgets_cat_usage_c_bb861b_idx"
                    ),
                ],
            },
        ),
    ]
