# Generated by Django 5.0.1 on 2025-09-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0007_categorysuggestion"),
        ("spaces", "0005_spacesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Scotia Debit 2105' or 'Cash Wallet'",
                        max_length=100,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("debit", "Debit Card"),
                            ("credit", "Credit Card"),
                            ("cash", "Cash"),
                            ("transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        default="debit",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "space")},
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment method to use for this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="budgets.paymentmethod",
            ),
        ),
    ]
