# Generated by Django 5.0.1 on 2025-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español")],
                default="en",
                max_length=10,
            ),
        ),
    ]
