# Generated by Django 5.0.1 on 2025-09-18 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spaces", "0005_spacesettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_requests",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications for approval requests",
                    ),
                ),
                (
                    "approval_results",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications when your requests are approved/rejected",
                    ),
                ),
                (
                    "space_events",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications for space events (new members, etc.)",
                    ),
                ),
                (
                    "budget_reminders",
                    models.BooleanField(
                        default=True, help_text="Receive budget and expense reminders"
                    ),
                ),
                (
                    "email_approval_requests",
                    models.BooleanField(
                        default=False, help_text="Also send approval requests via email"
                    ),
                ),
                (
                    "email_important_only",
                    models.BooleanField(
                        default=True,
                        help_text="Only send important notifications via email",
                    ),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("none", "No digest"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="none",
                        help_text="How often to send notification digest emails",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("approval_request", "Approval Request"),
                            ("approval_approved", "Request Approved"),
                            ("approval_rejected", "Request Rejected"),
                            ("approval_auto_approved", "Auto-approved"),
                            ("space_invite", "Space Invitation"),
                            ("member_joined", "New Member"),
                            ("member_left", "Member Left"),
                            ("budget_reminder", "Budget Reminder"),
                            ("expense_added", "Expense Added"),
                            ("general", "General"),
                        ],
                        default="general",
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level of the notification",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                (
                    "message",
                    models.TextField(help_text="Notification message", max_length=500),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to redirect when notification is clicked",
                        max_length=200,
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for action button (e.g., 'Approve', 'View')",
                        max_length=50,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has read this notification",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was marked as read",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this notification expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related space (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_583549_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="notificatio_expires_66996e_idx"
                    ),
                ],
            },
        ),
    ]
